export const stateData = [
  { name: 'Abia', status: 'Open', value: '87/100' },
  { name: 'Adamawa', status: 'Full', value: '100/100' },
  { name: 'Akwa Ibom', status: 'Open', value: '0/100' },
  { name: 'Anambra', status: 'Open', value: '44/100' },
  { name: 'Cross River', status: 'Open', value: '98/100' },
  { name: 'Bouchi', status: 'Full', value: '100/100' },
  { name: 'Bayelsa', status: 'Few Left', value: '5/100' },
  { name: 'Benue', status: 'Open', value: '73/100' },
  { name: 'Bono', status: 'Few Left', value: '21/100' },
  { name: 'Ektli', status: 'Open', value: '5/100' },
  { name: 'Borno', status: 'Open', value: '0/100' },
  { name: 'Delta', status: 'Full', value: '100/100' },
  { name: 'Ebonyi', status: 'Few Left', value: '19/100' },
  { name: 'Edo', status: 'Open', value: '0/100' },
  { name: 'Ekiti', status: 'Few Left', value: '3/100' },
  { name: 'Enugu', status: 'Full', value: '100/100' },
  { name: 'Gombe', status: 'Open', value: '76/100' },
  { name: 'Imo', status: 'Full', value: '100/100' },
  { name: 'Jigawa', status: 'Open', value: '64/100' },
  { name: 'Kaduna', status: 'Open', value: '30/100' },
  { name: 'Kano', status: 'Few Left', value: '9/100' },
  { name: 'Katsina', status: 'Open', value: '0/100' }
];
