export const stateData = [
  { name: 'Abia', status: 'open', value: '87/100' },
  { name: 'Adamawa', status: 'few left', value: '12/100' },
  { name: 'Akwa Ibom', status: 'full', value: '0/100' },
  { name: 'Anambra', status: 'open', value: '44/100' },
  { name: 'Cross River', status: 'open', value: 'Join Now' },
  { name: 'Bouchi', status: 'full', value: '100/100' },
  { name: 'Bayelsa', status: 'few left', value: '5/100' },
  { name: 'Benue', status: 'open', value: '73/100' },
  { name: 'Bono', status: 'few left', value: '21/100' },
  { name: 'Ektli', status: 'open', value: 'Join Now' },
  { name: 'Borno', status: 'open', value: '58/100' },
  { name: 'Delta', status: 'open', value: '82/100' },
  { name: 'Ebonyi', status: 'few left', value: '19/100' },
  { name: 'Edo', status: 'full', value: '0/100' },
  { name: 'Ekiti', status: 'few left', value: '3/100' },
  { name: 'Enugu', status: 'open', value: '55/100' },
  { name: 'Gombe', status: 'open', value: '76/100' },
  { name: 'Imo', status: 'few left', value: '13/100' },
  { name: 'Jigawa', status: 'open', value: '64/100' },
  { name: 'Kaduna', status: 'open', value: '30/100' },
  { name: 'Kano', status: 'few left', value: '9/100' },
  { name: 'Katsina', status: 'full', value: '0/100' }
];
